src/account/urls.py
from django.urls import path

from . import views

app_name = "account"

urlpatterns = [
    path("", views.LoginUserView.as_view(), name="login"),
    path("logout/", views.LogoutUserView.as_view(), name="logout"),
    path(
        "organizations/",
        views.OrganizationViewList.as_view(),
        name="organizations",
    ),
    path("users/add-user", views.CreateUserView.as_view(), name="add_user"),
    path("users/", views.ListUserView.as_view(), name="list"),
    path("<int:pk>/change/", views.UpdateUserView.as_view(), name="change"),
    path(
        "users/password-user/<int:pk>",
        views.UpdateUserPassword.as_view(),
        name="change_password_user",
    ),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

import debug_toolbar

urlpatterns = [
    path("", include("account.urls")),
    path("admin/", admin.site.urls),
    path("pitomnik/", include("pitomnik.urls")),
    path("vehicles/", include("vehicles.urls")),
    path("__debug__/", include(debug_toolbar.urls)),
    path("404/", TemplateView.as_view(template_name="404.html")),
    path("regiondata/", include("regionroad.urls")),
    path("accounting/", include("accounting.urls")),
    path("production/", include("production.urls")),
    path("archive/", include("archive.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/pitomnik/urls.py
from django.conf.urls import include
from django.urls import path

from .views.irrigation import (
    CreateIrrigationView,
    DeleteIrrigationView,
    AdminDeleteIrrigationView,
    IrrigationAdminByOrganization,
    IrrigationFilteredListView,
    IrrigationFilteredListViewAdmin,
    ListIrrigationImages,
    UpdateIrrigationView,
    AdminUpdateIrrigationView,
)
from .views.pitomnik import (
    AdminListPitomnikView,
    CreatePitomnikView,
    DeletePitomnikView,
    ListPitomnikImages,
    UpdatePitomnikView,
)
from .views.plant import (
    CreatePlantView,
    DeletePlantView,
    ListPlantView,
    UpdatePlantView,
)
from .views.planted_plant import (
    AdminListPlantedPlantView,
    CreatePlantedPlant,
    DeletePlantedPlant,
    DownloadPlantedPlant,
    ListPlantedPlantByRegionAdminView,
    ListPlantedPlantByRoadAdminView,
    ListPlantedPlantByRoadView,
    ListPlantedPlantImage,
    ListPlantedPlantView,
    LoadDistrictView,
    LoadPlantView,
    LoadRoadView,
    UpdateListPlantedPlantView,
)

from .views.landscape_job import (
    CreateLandScapeJob,
    DeleteLandScapeJob,
    AdminDeleteLandScapeJob,
    ListLandScapeJob,
    ListLandScapeJobAdmin,
    ListLandScapeJobByOrganizationAdmin,
    ListLandScapeJobImages,
    UpdateLandScapeJob,
    AdminUpdateLandScapeJob,
)
from .views.map import index, road_add, road_add_form, road_change, road_delete
from .views.new_irrigation import (
    CreateNewIrrigationView,
    DeleteNewIrrigationView,
    AdminDeleteNewIrrigationView,
    ListNewIrrigationAdminView,
    ListNewIrrigationByOrganizationAdmin,
    ListNewIrrigationImages,
    ListNewIrrigationView,
    UpdateNewIrrigationView,
    AdminUpdateNewIrrigationView,
)
from .views.pitomnik import ListPitomnikView
from .views.pitomnik_plant import (
    AdminPitomnikPlantListView,
    AdminPitomnikPlantStatsListView,
    DeletePitomnikPlantView,
    DownloadPitomnikPlants,
    ListPitomnikPlantImage,
    OrganizationPitomnikPlantStatsListView,
    PitomnikPlantCreateView,
    PitomnikPlantListView,
    RepublicPitomnikPlantListView,
    UpdatePitomnikPlantView,
    DownloadPlantedPlantss
)
from .views.pitomnik_saving_job import (
    CreatePitomnikSavingJob,
    DeletePitomnikSavingJob,
    ListPitomnikSavingJob,
    ListPitomnikSavingJobImages,
    UpdatePitomnikSavingJob,
)
from .views.saving_job import (
    CreateSavingJobView,
    DeleteSavingJobView,
    AdminDeleteSavingJobView,
    DownloadSavingJobView,
    ListSavingJobAdminView,
    ListSavingJobByOrganizationAdmin,
    ListSavingJobImages,
    ListSavingJobView,
    UpdateSavingJobView,
    UpdateAdminSavingJobView,
)

app_name = "pitomnik"

landscapejob_urls = [
    path("", ListLandScapeJob.as_view(), name="list"),
    path("add/", CreateLandScapeJob.as_view(), name="add"),
    path("<int:pk>/change/", UpdateLandScapeJob.as_view(), name="change"),
    path("<int:pk>/change_admin/", AdminUpdateLandScapeJob.as_view(), name="change_for_admin"),
    path("<int:pk>/delete/", DeleteLandScapeJob.as_view(), name="delete"),
    path("<int:pk>/delete_admin/", AdminDeleteLandScapeJob.as_view(), name="delete_for_admin"),
    path("admin/", ListLandScapeJobAdmin.as_view(), name="list_admin"),
    path(
        "region/<int:pk>/landscape/",
        ListLandScapeJobByOrganizationAdmin.as_view(),
        name="list_region_admin",
    ),
    path("<int:id>/images/", ListLandScapeJobImages.as_view(), name="images"),
]

pitomnik_urls = [
    path("", ListPitomnikView.as_view(), name="list"),
    path("<int:id>/", AdminListPitomnikView.as_view(), name="admin_list"),
    path("add/", CreatePitomnikView.as_view(), name="add"),
    path("<int:pk>/change/", UpdatePitomnikView.as_view(), name="change"),
    path("<int:pk>/delete/", DeletePitomnikView.as_view(), name="delete"),
    path("<int:id>/images/", ListPitomnikImages.as_view(), name="images"),
]

pitomnikplants_urls = [
    path("add/", PitomnikPlantCreateView.as_view(), name="add"),
    path("", PitomnikPlantListView.as_view(), name="list"),
    path("admin/", AdminPitomnikPlantListView.as_view(), name="admin_list"),
    path(
        "stats/organization/",
        OrganizationPitomnikPlantStatsListView.as_view(),
        name="pitomnik-plants-of-an-organization",
    ),
    path(
        "<int:pk>/change/",
        UpdatePitomnikPlantView.as_view(),
        name="change",
    ),
    path(
        "<int:pk>/delete/",
        DeletePitomnikPlantView.as_view(),
        name="delete",
    ),
    path(
        "<int:id>/images/",
        ListPitomnikPlantImage.as_view(),
        name="images",
    ),
    path(
        "stats/admin/<int:pk>/",
        AdminPitomnikPlantStatsListView.as_view(),
        name="admin-stats-by-organization",
    ),
    path(
        "stats/republic",
        RepublicPitomnikPlantListView.as_view(),
        name="republic-pitomnik-plants",
    ),
    path(
        "download/",
        DownloadPlantedPlantss.as_view(),
        name="download",
    ),
]
irrigation_urls = [
    path("add/", CreateIrrigationView.as_view(), name="add"),
    path("", IrrigationFilteredListView.as_view(), name="list"),
    path("<int:pk>/change/", UpdateIrrigationView.as_view(), name="change"),
    path("<int:pk>/change_admin/", AdminUpdateIrrigationView.as_view(), name="change_for_admin"),
    path("<int:pk>/delete/", DeleteIrrigationView.as_view(), name="delete"),
    path("<int:pk>/delete_admin/", AdminDeleteIrrigationView.as_view(), name="delete_for_admin"),
    path(
        "admin/", IrrigationFilteredListViewAdmin.as_view(), name="list_admin"
    ),
    path(
        "organization/<int:pk>/irrigation/",
        IrrigationAdminByOrganization.as_view(),
        name="list_region_admin",
    ),
    path(
        "<int:id>/images/",
        ListIrrigationImages.as_view(),
        name="images",
    ),
]

planted_plant_urls = [
    path("add/", CreatePlantedPlant.as_view(), name="add"),
    path("<int:pk>/delete", DeletePlantedPlant.as_view(), name="delete"),
    path("change/<int:pk>", UpdateListPlantedPlantView.as_view(), name="change"),
    path("ajax/plants/", LoadPlantView.as_view(), name="ajax_plant_list"),
    path(
        "ajax/districts/",
        LoadDistrictView.as_view(),
        name="ajax_district_list",
    ),
    path("", ListPlantedPlantView.as_view(), name="list"),
    path("<int:pk>/", AdminListPlantedPlantView.as_view(), name="admin_list"),
    path("ajax/roads/", LoadRoadView.as_view(), name="ajax_road_list"),
    path(
        "region/statistics/",
        ListPlantedPlantByRoadView.as_view(),
        name="road_statistics",
    ),
    path(
        "republic/statistics/",
        ListPlantedPlantByRegionAdminView.as_view(),
        name="republic_statistics",
    ),
    path(
        "region/<int:pk>/statistics/",
        ListPlantedPlantByRoadAdminView.as_view(),
        name="admin_road_statistics",
    ),
    path("<int:id>/images/", ListPlantedPlantImage.as_view(), name="images"),
    path("download/", DownloadPlantedPlant.as_view(), name="download"),
]
plant_urls = [
    path("", ListPlantView.as_view(), name="list"),
    path("add/", CreatePlantView.as_view(), name="add"),
    path("<int:pk>/change/", UpdatePlantView.as_view(), name="change"),
    path("<int:pk>/delete/", DeletePlantView.as_view(), name="delete"),
]

saving_job_urls = [
    path("add/", CreateSavingJobView.as_view(), name="add"),
    path("<int:pk>/change/", UpdateSavingJobView.as_view(), name="change"),
    path("<int:pk>/change_admin/", UpdateAdminSavingJobView.as_view(), name="change_for_admin"),
    path("<int:pk>/delete/", DeleteSavingJobView.as_view(), name="delete"),
    path("<int:pk>/delete_admin/", AdminDeleteSavingJobView.as_view(), name="delete_for_admin"),
    path("", ListSavingJobView.as_view(), name="list"),
    path("admin/", ListSavingJobAdminView.as_view(), name="list_admin"),
    path(
        "region/<int:pk>/savingjob",
        ListSavingJobByOrganizationAdmin.as_view(),
        name="list_region_admin",
    ),
    path(
        "download/<int:pk>/", DownloadSavingJobView.as_view(), name="download"
    ),
    path(
        "<int:id>/images/",
        ListSavingJobImages.as_view(),
        name="images",
    ),
]

new_irrigation_urls = [
    path("", ListNewIrrigationView.as_view(), name="list"),
    path("add/", CreateNewIrrigationView.as_view(), name="add"),
    path("<int:pk>/change/", UpdateNewIrrigationView.as_view(), name="change"),
    path("<int:pk>/change_admin/", AdminUpdateNewIrrigationView.as_view(), name="change_for_admin"),
    path("<int:pk>/delete/", DeleteNewIrrigationView.as_view(), name="delete"),
    path("<int:pk>/delete_admin/", AdminDeleteNewIrrigationView.as_view(), name="delete_for_admin"),
    path("admin/", ListNewIrrigationAdminView.as_view(), name="list_admin"),
    path(
        "region/<int:pk>/",
        ListNewIrrigationByOrganizationAdmin.as_view(),
        name="list_region_admin",
    ),
    path(
        "<int:id>/images/",
        ListNewIrrigationImages.as_view(),
        name="images",
    ),
]

pitomnik_saving_job = [
    path("", ListPitomnikSavingJob.as_view(), name="list"),
    path("add/", CreatePitomnikSavingJob.as_view(), name="add"),
    path("<int:pk>/change/", UpdatePitomnikSavingJob.as_view(), name="change"),
    path("<int:pk>/delete/", DeletePitomnikSavingJob.as_view(), name="delete"),
    path(
        "<int:id>/images/",
        ListPitomnikSavingJobImages.as_view(),
        name="images",
    ),
]

road_add_urls = [
    path('', road_add, name='road_add'),
    path('form/', road_add_form, name='road_add_form'),
    path('delete/<int:pk>/', road_delete, name='road_delete'),
    path('change/<int:pk>/', road_change, name='road_change'),
]

urlpatterns = [
    path("pitomnik/", include((pitomnik_urls, "pitomnik"))),
    path("pitomnikplants/", include((pitomnikplants_urls, "pitomnikplants"))),
    path("plantedplants/", include((planted_plant_urls, "plantedplants"))),
    path("plant/", include((plant_urls, "plant"))),

src/pitomnik/views/irrigation.py
from django.conf import settings
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db import transaction
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from django_filters.views import FilterView

from account.models import Organization
from pitomnik.base_mixin import BaseMixin
from pitomnik.filters import IrrigationFilter
from pitomnik.forms import (
    CreateIrrigationForm,
    IrrigationImageFormSet,
    UpdateIrrigationForm,
)
from pitomnik.models import Irrigation, IrrigationImage


class CreateIrrigationView(PermissionRequiredMixin, BaseMixin, CreateView):
    permission_required = [
        "pitomnik.add_irrigation",
    ]
    login_url = "account:login"
    model = Irrigation
    template_name = "pitomnik/irrigation/form.html"
    success_url = reverse_lazy("pitomnik:irrigation:list")
    form_class = CreateIrrigationForm

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data["images"] = IrrigationImageFormSet(
                self.request.POST, self.request.FILES
            )
        else:
            data["images"] = IrrigationImageFormSet()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        images = context["images"]
        with transaction.atomic():
            form.instance.added_by = self.request.user
            form.instance.organization = self.request.user.organization
            self.object = form.save()
            if images.is_valid():
                images.instance = self.object
                images.save()
        return super().form_valid(form)


class AdminUpdateIrrigationView(PermissionRequiredMixin, UpdateView):
    permission_required = "pitomnik.change_irrigation"
    model = Irrigation
    template_name = "pitomnik/irrigation/form.html"
    success_url = reverse_lazy("pitomnik:irrigation:list_admin")
    form_class = UpdateIrrigationForm

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data["images"] = IrrigationImageFormSet(
                self.request.POST, self.request.FILES, instance=self.object
            )
        else:
            data["images"] = IrrigationImageFormSet(instance=self.object)
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        images = context["images"]
        with transaction.atomic():
            # form.instance.added_by = self.request.user
            # form.instance.organization = self.request.user.organization
            self.object = form.save()
            if images.is_valid():
                images.instance = self.object
                images.save()
        return super().form_valid(form)


class UpdateIrrigationView(PermissionRequiredMixin, UpdateView):
    permission_required = "pitomnik.change_irrigation"
    model = Irrigation
    template_name = "pitomnik/irrigation/form.html"
    success_url = reverse_lazy("pitomnik:irrigation:list")
    form_class = UpdateIrrigationForm

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data["images"] = IrrigationImageFormSet(
                self.request.POST, self.request.FILES, instance=self.object
            )
        else:
            data["images"] = IrrigationImageFormSet(instance=self.object)
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        images = context["images"]
        with transaction.atomic():
            form.instance.added_by = self.request.user
            form.instance.organization = self.request.user.organization
            self.object = form.save()
            if images.is_valid():
                images.instance = self.object
                images.save()
        return super().form_valid(form)


class DeleteIrrigationView(PermissionRequiredMixin, DeleteView):
    permission_required = ["pitomnik.delete_irrigation"]
    model = Irrigation
    success_url = reverse_lazy("pitomnik:irrigation:list")


class AdminDeleteIrrigationView(PermissionRequiredMixin, DeleteView):
    permission_required = ["pitomnik.delete_irrigation"]
    model = Irrigation
    success_url = reverse_lazy("pitomnik:irrigation:list_admin")


class IrrigationFilteredListView(PermissionRequiredMixin, FilterView):
    model = Irrigation
    permission_required = [
        "pitomnik.view_irrigation",
    ]
    paginate_by = settings.IRRIGATION_PAGE_SIZE
    template_name = "pitomnik/irrigation/list.html"
    filterset_class = IrrigationFilter

    def get_queryset(self):
        organization = self.request.user.organization
        return Irrigation.objects.get_irrigation_by_organization(organization)


class IrrigationFilteredListViewAdmin(PermissionRequiredMixin, ListView):
    model = Irrigation
    permission_required = [
        "pitomnik.view_irrigation_admin",
    ]
    paginate_by = settings.IRRIGATION_PAGE_SIZE
    template_name = "pitomnik/irrigation/list_admin.html"
    queryset = Irrigation.objects.get_irrigation_list_for_admin()


class IrrigationAdminByOrganization(IrrigationFilteredListView):
    permission_required = "pitomnik.view_irrigation_admin"
    template_name = "pitomnik/irrigation/list_by_organization.html"

    def get_queryset(self):
        organization = get_object_or_404(Organization, pk=self.kwargs["pk"])
        return Irrigation.objects.get_irrigation_by_organization(organization)


class ListIrrigationImages(PermissionRequiredMixin, ListView):
    permission_required = "pitomnik.view_irrigationimage"
    template_name = "pitomnik/irrigation/images.html"

    def get_queryset(self):
        return IrrigationImage.objects.filter_by_irrigation(
            self.kwargs["id"], self.request.user
        )

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context["organization_id"] = get_object_or_404(Irrigation, pk=self.kwargs["id"]).organization_id
        return context

src/templates/pitomnik/pitomnik_plants/add.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block additional_css %}
    <link rel="stylesheet" href="{% static "vendor/select2-4.1.0-beta.1/dist/css/select2.min.css" %}">
    <link rel="stylesheet" href="{% static "vendor/css/datepiker-css/gijgo.min.css" %}">
{% endblock %}

{% block content %}
    <div class="d-flex justify-content-center align-items-center p-3">
        <div class="form-container bg-white shadow p-5 rounded w-100 ">
            {% crispy form %}
        </div>
    </div>
{% endblock %}

{% block additional_js %}
    <script src="{% static "vendor/js/datepiker-js/gijgo.min.js" %}"></script>
    <script src="{% static "vendor/select2-4.1.0-beta.1/dist/js/select2.js" %}"></script>
    <script>
        $('#id_readiness_date').datepicker({format: 'yyyy-mm-dd'});
        $('#id_planted_date').datepicker({format: 'yyyy-mm-dd'});
        $("#id_pitomnik").select2();
        $("#id_plant").select2();
        $('#id_plant_type').select2({minimumResultsForSearch: Infinity});

    </script>
    <script>
        let form = document.getElementById("click-only-once")
        let button = document.getElementById("form-button")
        form.addEventListener("submit", () => {
            button.setAttribute("disabled", "")
        })
    </script>
{% endblock %}

src/templates/pitomnik/pitomnik_plants/groupped_list.html
{% extends "base.html" %}
{% load pitomnik_tags %}
{% block content %}
    <div class="content-wrapper content-wrapper--with-bg">
        <div class="card">
            <div class="card-header">
                <span><p><i class="fas fa-bars"></i> Ўсимликлар</p></span>
            </div>
            <div CLASS="row treeTypes">
                <div class="col-lg-3">
                    <a class="{% if section == "None" %}pressed{% endif %}"
                       href="{% url "pitomnik:pitomnikplants:pitomnik-plants-of-an-organization" %}">Ҳаммаси</a>
                </div>
                <div class="col-lg-3">
                    <a class="{% if section == "bush" %}pressed{% endif %}"
                       href="{% url "pitomnik:pitomnikplants:pitomnik-plants-of-an-organization" %}?type=bush">Буталар</a>
                </div>
                <div class="col-lg-3">
                    <a class="{% if section == "leaf_shaped_tree" %}pressed{% endif %}"
                       href="{% url "pitomnik:pitomnikplants:pitomnik-plants-of-an-organization" %}?type=leaf_shaped_tree">Япроқ
                        баргли дарахт</a>
                </div>
                <div class="col-lg-3">
                    <a class="{% if section == "pitomnik_plant_coniferous_tree" %}pressed{% endif %}"
                       href="{% url "pitomnik:pitomnikplants:pitomnik-plants-of-an-organization" %}?type=coniferous_tree">Игна
                        баргли дарахт</a>
                </div>
            </div>

            <div id="table" class="table-responsive">
                <table class="table plant">
                    <thead>
                    <td>№</td>
                    <td>Ўсимлик номи</td>
                    <td>Экилган миқдори (барчаси)</td>
                    <td>Экилган миқдори (тайёри)</td>
                    <td>Экилган майдон</td>
                    </thead>
                    <tbody>
                    {% for pitomnik_plant_item in pitomnik_plant_stats %}
                        <tr>
                            <td>{{ page_obj.start_index|add:forloop.counter0 }}</td>
                            <td>{{ pitomnik_plant_item.name }}</td>
                            <td>{{ pitomnik_plant_item.total_plant_quantity }}</td>
                            <td>{{ pitomnik_plant_item.ready_plant_quantity }}</td>
                            <td>{{ pitomnik_plant_item.field_to_be_planted | get_decimal}}</td>
                        </tr>

                        {% empty %}
                        <tr>
                            <td colspan="9"></td>
                        </tr>
                        <tr>
                            <td colspan="9">Питомникларга ўсимликлар қошилмаган</td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <td class="alert alert-primary"></td>
                        <td class="alert alert-primary">Жами</td>
                        <td class="alert alert-primary">{{ total_plant }} </td>
                        <td class="alert alert-primary">{{ total_ready_plant }} </td>
                        <td class="alert alert-primary">{{ total_field | get_decimal }}</td>
                    </tr>
                    </tbody>
                </table>
                {% include "pitomnik_plant_pagination.html" %}
            </div>
        </div>
    </div>
    </div>

{% endblock %}

src/templates/pitomnik/pitomnik_plants/stats.html
{% extends "base.html" %}
{% load pitomnik_tags %}
{% block content %}

    <div class="content-wrapper content-wrapper--with-bg">
        <div class="card">
            <div class="card-header">
                {% if request.resolver_match.view_name == "pitomnik:pitomnikplants:admin-stats-by-organization" %}
                    <a class="text-decoration-none"
                       href="{% url "account:organizations" %}"><i
                            class="fas fa-arrow-left text-white"></i></a>
                {% else %}
                    <span></span>
                {% endif %}

            </div>
            <div CLASS="row treeTypes">
                <div class="col-lg-3">
                    <a class="{% if section == "pitomnik_plant_None" %}pressed{% endif %}"
                       href="{% url "pitomnik:pitomnikplants:admin-stats-by-organization" pk %}">Ҳаммаси </a>
                </div>
                <div class="col-lg-3">
                    <a class="{% if section == "pitomnik_plant_bush" %}pressed{% endif %}"
                       href="{% url "pitomnik:pitomnikplants:admin-stats-by-organization" pk %}?type=bush">Буталар</a>
                </div>
                <div class="col-lg-3">
                    <a class="{% if section == "pitomnik_plant_leaf_shaped_tree" %}pressed{% endif %}"
                       href="{% url "pitomnik:pitomnikplants:admin-stats-by-organization" pk %}?type=leaf_shaped_tree">Япроқ
                        баргли дарахт</a>
                </div>
                <div class="col-lg-3">
                    <a class="{% if section == "pitomnik_plant_coniferous_tree" %}pressed{% endif %}"
                       href="{% url "pitomnik:pitomnikplants:admin-stats-by-organization" pk %}?type=coniferous_tree">Игна
                        баргли дарахт</a>
                </div>
            </div>

            <div class="card-body pt-1">
                <div id="table" class="table-responsive">
                    <table class="table plant">
                        <thead>
                        <td>№</td>
                        <td>Ўсимлик номи</td>
                        <td>Экилган миқдори (барчаси)</td>
                        <td>Экилган миқдори (тайёри)</td>
                        <td>Экилган майдон</td>
                        </thead>
                        <tbody>
                        {% for pitomnik_plant_stat in pitomnik_plant_stats %}
                            <tr>
                                <td>
                                    {{ page_obj.start_index|add:forloop.counter0 }}</td>
                                <td>{{ pitomnik_plant_stat.name }}</td>
                                <td>{{ pitomnik_plant_stat.total_plant_quantity }}</td>
                                <td>{{ pitomnik_plant_stat.ready_plant_quantity }}</td>
                                <td>{{ pitomnik_plant_stat.field_to_be_planted | get_decimal }}</td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td colspan="9"></td>
                            </tr>
                            <tr>
                                <td colspan="9">Питомникларга ўсимликлар
                                    қошилмаган
                                </td>
                            </tr>
                        {% endfor %}
                        <tr>
                            <td class="alert alert-primary"></td>
                            <td class="alert alert-primary">Жами</td>
                            <td class="alert alert-primary">{{ total_plant }} </td>
                            <td class="alert alert-primary">{{ total_ready_plant }} </td>
                            <td class="alert alert-primary">{{ total_field | get_decimal }}</td>
                        </tr>
                        </tbody>
                    </table>
                    {% include "pitomnik_plant_pagination.html" %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}