src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

import debug_toolbar

urlpatterns = [
    path("", include("account.urls")),
    path("admin/", admin.site.urls),
    path("pitomnik/", include("pitomnik.urls")),
    path("vehicles/", include("vehicles.urls")),
    path("__debug__/", include(debug_toolbar.urls)),
    path("404/", TemplateView.as_view(template_name="404.html")),
    path("regiondata/", include("regionroad.urls")),
    path("accounting/", include("accounting.urls")),
    path("production/", include("production.urls")),
    path("archive/", include("archive.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/pitomnik/urls.py
from django.conf.urls import include
from django.urls import path

from .views.irrigation import (
    CreateIrrigationView,
    DeleteIrrigationView,
    AdminDeleteIrrigationView,
    IrrigationAdminByOrganization,
    IrrigationFilteredListView,
    IrrigationFilteredListViewAdmin,
    ListIrrigationImages,
    UpdateIrrigationView,
    AdminUpdateIrrigationView,
)
from .views.pitomnik import (
    AdminListPitomnikView,
    CreatePitomnikView,
    DeletePitomnikView,
    ListPitomnikImages,
    UpdatePitomnikView,
)
from .views.plant import (
    CreatePlantView,
    DeletePlantView,
    ListPlantView,
    UpdatePlantView,
)
from .views.planted_plant import (
    AdminListPlantedPlantView,
    CreatePlantedPlant,
    DeletePlantedPlant,
    DownloadPlantedPlant,
    ListPlantedPlantByRegionAdminView,
    ListPlantedPlantByRoadAdminView,
    ListPlantedPlantByRoadView,
    ListPlantedPlantImage,
    ListPlantedPlantView,
    LoadDistrictView,
    LoadPlantView,
    LoadRoadView,
    UpdateListPlantedPlantView,
)

from .views.landscape_job import (
    CreateLandScapeJob,
    DeleteLandScapeJob,
    AdminDeleteLandScapeJob,
    ListLandScapeJob,
    ListLandScapeJobAdmin,
    ListLandScapeJobByOrganizationAdmin,
    ListLandScapeJobImages,
    UpdateLandScapeJob,
    AdminUpdateLandScapeJob,
)
from .views.map import index, road_add, road_add_form, road_change, road_delete
from .views.new_irrigation import (
    CreateNewIrrigationView,
    DeleteNewIrrigationView,
    AdminDeleteNewIrrigationView,
    ListNewIrrigationAdminView,
    ListNewIrrigationByOrganizationAdmin,
    ListNewIrrigationImages,
    ListNewIrrigationView,
    UpdateNewIrrigationView,
    AdminUpdateNewIrrigationView,
)
from .views.pitomnik import ListPitomnikView
from .views.pitomnik_plant import (
    AdminPitomnikPlantListView,
    AdminPitomnikPlantStatsListView,
    DeletePitomnikPlantView,
    DownloadPitomnikPlants,
    ListPitomnikPlantImage,
    OrganizationPitomnikPlantStatsListView,
    PitomnikPlantCreateView,
    PitomnikPlantListView,
    RepublicPitomnikPlantListView,
    UpdatePitomnikPlantView,
    DownloadPlantedPlantss
)
from .views.pitomnik_saving_job import (
    CreatePitomnikSavingJob,
    DeletePitomnikSavingJob,
    ListPitomnikSavingJob,
    ListPitomnikSavingJobImages,
    UpdatePitomnikSavingJob,
)
from .views.saving_job import (
    CreateSavingJobView,
    DeleteSavingJobView,
    AdminDeleteSavingJobView,
    DownloadSavingJobView,
    ListSavingJobAdminView,
    ListSavingJobByOrganizationAdmin,
    ListSavingJobImages,
    ListSavingJobView,
    UpdateSavingJobView,
    UpdateAdminSavingJobView,
)

app_name = "pitomnik"

landscapejob_urls = [
    path("", ListLandScapeJob.as_view(), name="list"),
    path("add/", CreateLandScapeJob.as_view(), name="add"),
    path("<int:pk>/change/", UpdateLandScapeJob.as_view(), name="change"),
    path("<int:pk>/change_admin/", AdminUpdateLandScapeJob.as_view(), name="change_for_admin"),
    path("<int:pk>/delete/", DeleteLandScapeJob.as_view(), name="delete"),
    path("<int:pk>/delete_admin/", AdminDeleteLandScapeJob.as_view(), name="delete_for_admin"),
    path("admin/", ListLandScapeJobAdmin.as_view(), name="list_admin"),
    path(
        "region/<int:pk>/landscape/",
        ListLandScapeJobByOrganizationAdmin.as_view(),
        name="list_region_admin",
    ),
    path("<int:id>/images/", ListLandScapeJobImages.as_view(), name="images"),
]

pitomnik_urls = [
    path("", ListPitomnikView.as_view(), name="list"),
    path("<int:id>/", AdminListPitomnikView.as_view(), name="admin_list"),
    path("add/", CreatePitomnikView.as_view(), name="add"),
    path("<int:pk>/change/", UpdatePitomnikView.as_view(), name="change"),
    path("<int:pk>/delete/", DeletePitomnikView.as_view(), name="delete"),
    path("<int:id>/images/", ListPitomnikImages.as_view(), name="images"),
]

pitomnikplants_urls = [
    path("add/", PitomnikPlantCreateView.as_view(), name="add"),
    path("", PitomnikPlantListView.as_view(), name="list"),
    path("admin/", AdminPitomnikPlantListView.as_view(), name="admin_list"),
    path(
        "stats/organization/",
        OrganizationPitomnikPlantStatsListView.as_view(),
        name="pitomnik-plants-of-an-organization",
    ),
    path(
        "<int:pk>/change/",
        UpdatePitomnikPlantView.as_view(),
        name="change",
    ),
    path(
        "<int:pk>/delete/",
        DeletePitomnikPlantView.as_view(),
        name="delete",
    ),
    path(
        "<int:id>/images/",
        ListPitomnikPlantImage.as_view(),
        name="images",
    ),
    path(
        "stats/admin/<int:pk>/",
        AdminPitomnikPlantStatsListView.as_view(),
        name="admin-stats-by-organization",
    ),
    path(
        "stats/republic",
        RepublicPitomnikPlantListView.as_view(),
        name="republic-pitomnik-plants",
    ),
    path(
        "download/",
        DownloadPlantedPlantss.as_view(),
        name="download",
    ),
]
irrigation_urls = [
    path("add/", CreateIrrigationView.as_view(), name="add"),
    path("", IrrigationFilteredListView.as_view(), name="list"),
    path("<int:pk>/change/", UpdateIrrigationView.as_view(), name="change"),
    path("<int:pk>/change_admin/", AdminUpdateIrrigationView.as_view(), name="change_for_admin"),
    path("<int:pk>/delete/", DeleteIrrigationView.as_view(), name="delete"),
    path("<int:pk>/delete_admin/", AdminDeleteIrrigationView.as_view(), name="delete_for_admin"),
    path(
        "admin/", IrrigationFilteredListViewAdmin.as_view(), name="list_admin"
    ),
    path(
        "organization/<int:pk>/irrigation/",
        IrrigationAdminByOrganization.as_view(),
        name="list_region_admin",
    ),
    path(
        "<int:id>/images/",
        ListIrrigationImages.as_view(),
        name="images",
    ),
]

planted_plant_urls = [
    path("add/", CreatePlantedPlant.as_view(), name="add"),
    path("<int:pk>/delete", DeletePlantedPlant.as_view(), name="delete"),
    path("change/<int:pk>", UpdateListPlantedPlantView.as_view(), name="change"),
    path("ajax/plants/", LoadPlantView.as_view(), name="ajax_plant_list"),
    path(
        "ajax/districts/",
        LoadDistrictView.as_view(),
        name="ajax_district_list",
    ),
    path("", ListPlantedPlantView.as_view(), name="list"),
    path("<int:pk>/", AdminListPlantedPlantView.as_view(), name="admin_list"),
    path("ajax/roads/", LoadRoadView.as_view(), name="ajax_road_list"),
    path(
        "region/statistics/",
        ListPlantedPlantByRoadView.as_view(),
        name="road_statistics",
    ),
    path(
        "republic/statistics/",
        ListPlantedPlantByRegionAdminView.as_view(),
        name="republic_statistics",
    ),
    path(
        "region/<int:pk>/statistics/",
        ListPlantedPlantByRoadAdminView.as_view(),
        name="admin_road_statistics",
    ),
    path("<int:id>/images/", ListPlantedPlantImage.as_view(), name="images"),
    path("download/", DownloadPlantedPlant.as_view(), name="download"),
]
plant_urls = [
    path("", ListPlantView.as_view(), name="list"),
    path("add/", CreatePlantView.as_view(), name="add"),
    path("<int:pk>/change/", UpdatePlantView.as_view(), name="change"),
    path("<int:pk>/delete/", DeletePlantView.as_view(), name="delete"),
]

saving_job_urls = [
    path("add/", CreateSavingJobView.as_view(), name="add"),
    path("<int:pk>/change/", UpdateSavingJobView.as_view(), name="change"),
    path("<int:pk>/change_admin/", UpdateAdminSavingJobView.as_view(), name="change_for_admin"),
    path("<int:pk>/delete/", DeleteSavingJobView.as_view(), name="delete"),
    path("<int:pk>/delete_admin/", AdminDeleteSavingJobView.as_view(), name="delete_for_admin"),
    path("", ListSavingJobView.as_view(), name="list"),
    path("admin/", ListSavingJobAdminView.as_view(), name="list_admin"),
    path(
        "region/<int:pk>/savingjob",
        ListSavingJobByOrganizationAdmin.as_view(),
        name="list_region_admin",
    ),
    path(
        "download/<int:pk>/", DownloadSavingJobView.as_view(), name="download"
    ),
    path(
        "<int:id>/images/",
        ListSavingJobImages.as_view(),
        name="images",
    ),
]

new_irrigation_urls = [
    path("", ListNewIrrigationView.as_view(), name="list"),
    path("add/", CreateNewIrrigationView.as_view(), name="add"),
    path("<int:pk>/change/", UpdateNewIrrigationView.as_view(), name="change"),
    path("<int:pk>/change_admin/", AdminUpdateNewIrrigationView.as_view(), name="change_for_admin"),
    path("<int:pk>/delete/", DeleteNewIrrigationView.as_view(), name="delete"),
    path("<int:pk>/delete_admin/", AdminDeleteNewIrrigationView.as_view(), name="delete_for_admin"),
    path("admin/", ListNewIrrigationAdminView.as_view(), name="list_admin"),
    path(
        "region/<int:pk>/",
        ListNewIrrigationByOrganizationAdmin.as_view(),
        name="list_region_admin",
    ),
    path(
        "<int:id>/images/",
        ListNewIrrigationImages.as_view(),
        name="images",
    ),
]

pitomnik_saving_job = [
    path("", ListPitomnikSavingJob.as_view(), name="list"),
    path("add/", CreatePitomnikSavingJob.as_view(), name="add"),
    path("<int:pk>/change/", UpdatePitomnikSavingJob.as_view(), name="change"),
    path("<int:pk>/delete/", DeletePitomnikSavingJob.as_view(), name="delete"),
    path(
        "<int:id>/images/",
        ListPitomnikSavingJobImages.as_view(),
        name="images",
    ),
]

road_add_urls = [
    path('', road_add, name='road_add'),
    path('form/', road_add_form, name='road_add_form'),
    path('delete/<int:pk>/', road_delete, name='road_delete'),
    path('change/<int:pk>/', road_change, name='road_change'),
]

urlpatterns = [
    path("pitomnik/", include((pitomnik_urls, "pitomnik"))),
    path("pitomnikplants/", include((pitomnikplants_urls, "pitomnikplants"))),
    path("plantedplants/", include((planted_plant_urls, "plantedplants"))),
    path("plant/", include((plant_urls, "plant"))),

src/regionroad/urls.py
from django.urls import include, path

from regionroad.views import (
    GetDistrictPlantQuantity,
    GetRegionDistrict,
    GetRegionPlantQuantity,
    GetRegions,
    GetRepublicPlantQuantity,
    RoadDistrictCreateView,
    RoadDistrictDeleteView,
    RoadDistrictListView,
    RoadDistrictUpdateView,
    GetUzbJson
)

from .views import GetJson

app_name = "regionroad"
api_urls = [
    path("coordinates/", GetJson.as_view(), name="api_coordinates"),
    path("regions/", GetRegions.as_view(), name="api_regions"),
    path(
        "<int:pk>/districts/",
        GetRegionDistrict.as_view(),
        name="api_districts",
    ),
    path(
        "<int:pk>/districtplants/",
        GetDistrictPlantQuantity.as_view(),
        name="api_districtplants",
    ),
    path(
        "<int:pk>/regionplants/",
        GetRegionPlantQuantity.as_view(),
        name="api_regionplants",
    ),
    path("cordinates/", GetUzbJson.as_view(), name="uzb_json"),
    path("republicplants/", GetRepublicPlantQuantity.as_view(), name="api_republicplants")
]

urlpatterns = [
    path("list/", RoadDistrictListView.as_view(), name="road-district-list"),
    path(
        "create/",
        RoadDistrictCreateView.as_view(),
        name="road-district-create",
    ),
    path(
        "<int:pk>/update/",
        RoadDistrictUpdateView.as_view(),
        name="road-district-update",
    ),
    path(
        "<int:pk>/delete/",
        RoadDistrictDeleteView.as_view(),
        name="road-district-delete",
    ),
    path("api/", include((api_urls, "api"))),
]

src/templates/road_district/create.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}
 <div class="d-flex justify-content-center align-items-center p-4">
        <div class="form-container bg-white shadow p-5 rounded w-100 h-100">
            <form id="click-only-once" method='post' action="">
                {% csrf_token %}
                {{ form | crispy }}
                <div class="modal-footer">
                    <a href="{% url "regionroad:road-district-list" %}" class="btn btn-secondary text-white ">Орқага қайтиш</a>
                    <button id="form-button" type="submit" class="btn btn-success">Қўшиш</button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

{% block additional_js %}
    <script>
        let form = document.getElementById("click-only-once")
        let button = document.getElementById("form-button")
        form.addEventListener("submit", () => {
            button.setAttribute("disabled", "")
        })
    </script>
{% endblock %}

src/templates/road_district/list.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load pitomnik_tags %}
{% block content %}
{% block additional_css %}
    <link rel="stylesheet" href="{% static "vendor/select2-4.1.0-beta.1/dist/css/select2.min.css" %}">
{% endblock %}
 <div class="content-wrapper content-wrapper--with-bg">
        <div class="card">
            <div class="card-header">
                <span><p><i class="fas fa-bars"></i> Туман бўйича йўллар</p></span>
            </div>

            <div class="card-body pt-0">

                <div  id="table" class="table-responsive">
                    <table class="table plant">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Йўл номи</th>
                                <th>Йўл коди</th>
                                <th>Туман</th>
                                <th>Йўл узунлиги</th>
                                <th>Кўкаламзорлаштиришга талаб</th>
                                <th>Ўзгартириш & Ўчириш</th>
                            </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <form>
                                <td></td>
                                <td>
                                    {{ filter.form.road | as_crispy_field }}
                                </td>
                                <td>
                                     {{ filter.form.road__code | as_crispy_field }}
                                </td>
                                <td colspan="3"></td>
                                <td class="d-flex justify-content-end">
                                    <button type="submit"
                                            class="btn btn-secondary">
                                        <i class="fas fa-search"></i>
                                    </button>
                                </td>
                            </form>
                        </tr>
                        {% for road_district in object_list  %}
                            <tr>
                            <td>{{ page_obj.start_index|add:forloop.counter0 }}</td>
                            <td>{{ road_district.road }}</td>
                            <td>{{ road_district.road.code }}</td>
                            <td>{{ road_district.district }}</td>
                            <td>{{ road_district.road_from | get_decimal }}-{{ road_district.road_to | get_decimal }}</td>
                            <td>{{ road_district.requirement | get_decimal }}</td>
                            <td>
                                <a href="{% url "regionroad:road-district-update" road_district.pk %}" class="btn btn-warning">
                                        <i class="fas fa-pencil-alt text-white"></i>
                                    </a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    {% include "pagination.html" %}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block additional_js %}
    <script src="{% static "vendor/select2-4.1.0-beta.1/dist/js/select2.js" %}"></script>
    <script src="{% static "local/js/road_select2.js" %}"></script>
    <script>
        $(document).ready(function () {
            $("#id_road").select2();
        });
    </script>
{% endblock %}

src/templates/road_district/road_add.html
{#{% extends "base.html" %}#}
{#{% load static %}#}
{#{% load crispy_forms_tags %}#}
{#{% block content %}#}
{##}
{#    <div class="d-flex justify-content-center align-items-center p-3">#}
{#        <div class="form-container bg-white shadow p-5 rounded w-100 ">#}
{#            <form method='post' action="">#}
{#                {% csrf_token %}#}
{#                {{ organization }}#}
{#                #}
{#            </form>#}
{#        </div>#}
{#    </div>#}
{#{% endblock %}#}
{##}
{#{% block additional_js %}#}
{#    <script src="{% static "vendor/js/multiselect.js" %}"></script>#}
{#    <script src="{% static "local/js/multiselect.js" %}"></script>#}
{#{% endblock %}#}

{% extends "base.html" %}
{% load static %}
{% load mathfilters %}
{% load pitomnik_tags %}
{% block content %}

    <div class="tableCont">
        <div class="tableHeader">
            <h3 class="text-white m-0">{{ organization }}</h3>
            <span></span>
        </div>
        <div class="d-flex ml-auto px-4 py-4">
            <form action="{% url 'pitomnik:road_add' %}" method="get" class="d-flex ml-auto px-4">
                {% csrf_token %}
                <input name="search_input"/>
                <button type="submit" class="btn btn-secondary refreshing_button">
                    <i class="fas fa-search refreshing_button"></i>
                </button>
            </form>
            {% include "road_district/road_add_button.html" %}
        </div>

        <div class="tableContent">
            <div class="table-responsive table-scrollbar">
                <table class="table">
                    <thead>
                    <tr>
                        <th rowspan="2">#</th>
                        <th rowspan="2">Йўл номи</th>
                        <th rowspan="2">Йўл тури</th>
                        <th rowspan="2">Туман номи</th>
                        <th rowspan="2">Aмаллар</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for object in page_obj %}
                            <tr>
                                <td>{{ page_obj.start_index|add:forloop.counter0 }}</td>
                                <td>{{ object.road.code }}  {{ object.road.title }}</td>
                                <td>{{ object.road.road_type |road_type_label }}</td>
                                <td>{{ object.district.name }}</td>
                                <td>
                                    {% include 'road_district/road_change.html' with change_url='pitomnik:road_change' id=object.id %}
                                    {% include 'road_district/road_delete.html' with id=object.id delete_url="pitomnik:road_delete" message="Белгиланган йўл ўчирилади!" %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% include "pagination.html" %}
            </div>
        </div>
    </div>
{% endblock content %}

src/templates/road_district/road_add_button.html
<div class="table-add d-flex justify-content-between">
    <p></p>
    <a href="{% url 'pitomnik:road_add_form' %}"
       class="btn btn-warning">
        <i class="fas fa-plus text-light"></i>
    </a>
</div>

src/templates/road_district/road_add_change.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block additional_css %}
    <link rel="stylesheet" href="{% static "vendor/select2-4.1.0-beta.1/dist/css/select2.min.css" %}">
    <link rel="stylesheet" href="{% static "vendor/css/datepiker-css/gijgo.min.css" %}">
{% endblock %}

{% block content %}
    <div class="d-flex justify-content-center align-items-center p-3">
        <div class="form-container bg-white shadow p-5 rounded w-100 ">
            <form action="{% url 'pitomnik:road_change' pk %}" method="post" name="road_form">
                {% csrf_token %}
                <label>Йўл коди</label>
                <input class="form-control m-3" type="text" value="{{ road_info.code }}" name="road_code">
                <label>Йўл номи</label>
                <input class="form-control m-3" type="text" value="{{ road_info.title }}" name="road">
                <label>Йўл қисми</label>
                <input class="form-control m-3" type="text" value="{{ road_slice }}" name="road_slice">
                <label>Йўл тури</label>
                <select class="form-control m-3" name="road_type">
                    {% if road_info.road_type == 1 %}
                        <option selected name="road_type" value="Халқаро">Халқаро</option>
                    {% endif %}
                    {% if road_info.road_type == 2 %}
                        <option selected name="road_type" value="Давлат">Давлат</option>
                    {% endif %}
                    {% if road_info.road_type == 3 %}
                        <option selected name="road_type" value="Маҳаллий">Маҳаллий</option>
                    {% endif %}
                    <option name="road_type" value="Халқаро">Халқаро</option>
                    <option name="road_type" value="Давлат">Давлат</option>
                    <option name="road_type" value="Маҳаллий">Маҳаллий</option>
                </select>
                <label>Туман/Шаҳар номи</label>
                <select class="form-control m-3" name="district">
                    <option selected name="district" value="{{ district_info.name }}">{{ district_info.name }}</option>
                    {% for i in district_name_choices %}
                        <option name="district" value="{{ i }}">{{ i }}</option>
                    {% endfor %}
                </select>
                <button class="btn btn-secondary"><a class="text-white" href="{% url 'pitomnik:road_add' %}">Орқага</a></button>
                <button class="btn btn-primary send_form_btn" type="submit">Сақлаш</button>
            </form>
        </div>
    </div>
{% endblock %}

{% block additional_js %}
    <script>
        $('.send_form_btn').on('click', function(){
            road_form.submit();
        });
    </script>
{% endblock %}

src/templates/road_district/road_add_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block additional_css %}
    <link rel="stylesheet" href="{% static "vendor/select2-4.1.0-beta.1/dist/css/select2.min.css" %}">
    <link rel="stylesheet" href="{% static "vendor/css/datepiker-css/gijgo.min.css" %}">
{% endblock %}

{% block content %}
    <div class="d-flex justify-content-center align-items-center p-3">
        <div class="form-container bg-white shadow p-5 rounded w-100 ">
            <form action="{% url 'pitomnik:road_add_form' %}" method="post" name="road_form">
                {% csrf_token %}
                {% crispy form %}
                <button class="btn btn-secondary"><a class="text-white" href="{% url 'pitomnik:road_add' %}">Орқага</a></button>
                <button class="btn btn-primary send_form_btn" type="submit">Сақлаш</button>
            </form>
        </div>
    </div>
{% endblock %}

{% block additional_js %}
    <script>
        $('.send_form_btn').on('click', function(){
            road_form.submit();
        });
    </script>
{% endblock %}

src/templates/road_district/road_change.html
<a href="{% url change_url id %}"
   class="btn btn-success">
    <i class="fas fa-pencil-alt text-white"></i>
</a>

src/templates/road_district/road_delete.html
<!-- Button trigger modal -->
<button type="button"
        class="btn btn-danger "
        data-toggle="modal"
        data-target="#model-id{{ id }}">
    <i class="far fa-trash-alt text-white"></i>
</button>
<!-- Modal -->
<div class="modal fade"
     id="model-id{{ id }}"
     tabindex="-1" role="dialog"
     aria-labelledby="exampleModalCenterTitle"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered d-flex justify-content-center"
         role="document">
        <div class="modal-content border-0"
             style="width: 400px">
            <div class="modal-body">
                <h1>Ўчирилади</h1>
                <p>
                    {{ message }}
                </p>
                <div class="w-100 d-flex justify-content-between align-items-center">
                    <form action="{% url delete_url id %}"
                          method="post"
                          style="display: contents">
                        {% csrf_token %}
                        <button type="button"
                                style="flex: 0.45"
                                class="btn btn-outline-secondary"
                                data-dismiss="modal">
                            Ёқ
                        </button>
                        <button type="submit"
                                style="flex: 0.45"
                                class="rounded-lg btn btn-danger">
                            Ҳа
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

src/templates/road_district/update.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}
 <div class="d-flex justify-content-center align-items-center p-4">
        <div class="form-container bg-white shadow p-5 rounded w-100 h-100">
            <form id="click-only-once" method='post' action="">
                {% csrf_token %}
                {{ form | crispy }}
                <div class="modal-footer">
                    <a href="{% url "regionroad:road-district-list" %}" class="btn btn-secondary text-white ">Орқага қайтиш</a>
                    <button id="form-button" type="submit" class="btn btn-success">Ўзгартириш</button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

{% block additional_js %}
    <script>
        let form = document.getElementById("click-only-once")
        let button = document.getElementById("form-button")
        form.addEventListener("submit", () => {
            button.setAttribute("disabled", "")
        })
    </script>
{% endblock %}